(reference "System.Windows.Forms")
(reference "System.Drawing")
(using "System.Windows.forms")
(using "System.Drawing")
(using "LSharp.Interpreter")
(call Banner Program)
(= top (new TopLoop))
(run top)